server {
    listen 127.0.0.1:8080;
    root www/example;

    index index.html index.htm;
    allow_methods GET POST DELETE;

    location /example {
    }

    location /example/test_subfolder {
    }

    location /cgi-py {
        cgi_allow_methods GET POST;
        allow_uploads on;
        cgi_handler .py /usr/bin/python3;
    }
}
