server {
    listen 127.0.0.1:8080;
    root www/site1;

    index index.html index.htm;
    allow_methods GET POST DELETE;

    location /old  {
        return 302 /files;
    }

    location /pages {
        autoindex off;
    }

    location /images {
    }

    location /files {
        autoindex on;
    }
}
