server {
    listen 5050;
    listen 8080;
    root www/vitepress_docs;

    index index.html index.htm;
    error_page 404 /404.html;
    error_page 403 /404.html;

    location / {
        error_page 404 /404_route_specific1.html;
    }

    location /override/ {
        error_page 404 /404_route_specific2.html;
    }

    location /nooverride/ {
        
    }   
}
