server {
    listen 8080;

    root ./www/YoupiBanane;

    cgi_handler .bla /cgi-bin/cgi_tester;
    cgi_allow_methods POST;

    location / {
        allow_methods GET;
    }

    location /post_body {
        allow_methods POST;
        client_max_body_size 100;
        allow_uploads on;
        upload_store ./www/YoupiBanane/uploads;
    }

    location /directory/ {
        allow_methods GET;
        index youpi.bad_extension;
    }
}
